name: Test

on:
  pull_request:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18"]
    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
      - run: make build
      - run: |
          make build-static
          file esacc | grep 'statically linked'
